<?php

/**
 * BaseEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $entry_date
 * @property time $start_time
 * @property time $stop_time
 * 
 * @method date  getEntryDate()  Returns the current record's "entry_date" value
 * @method time  getStartTime()  Returns the current record's "start_time" value
 * @method time  getStopTime()   Returns the current record's "stop_time" value
 * @method Entry setEntryDate()  Sets the current record's "entry_date" value
 * @method Entry setStartTime()  Sets the current record's "start_time" value
 * @method Entry setStopTime()   Sets the current record's "stop_time" value
 * 
 * @package    timesheet
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entries');
        $this->hasColumn('entry_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('start_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('stop_time', 'time', null, array(
             'type' => 'time',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}