<?php

/**
 * Entry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    timesheet
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Entry extends BaseEntry
{
}
