homepage:
  url:   /
  param: {module: entries, action: index}

entry:
  url:  /:year/:month
  param: {module: entries, action: index}
  requirements: {year: \d+, month: \d+}

default_index:
  url:   /:module
  param: {action: index}

default:
  url:   /:module/:action/*
